// import type { Metadata } from "next";

"use client"
import Nav from "@/components/Layout/Nav";
import SideBar from "@/components/Layout/SideBar";
import { useState } from "react";

// export const metadata: Metadata = {
//   title: "Apodex",
//   description: "Generated by create next app",
// };




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [open, setOpen] = useState(false);
  return (
    <div className="h-full min-h-screen max-h-screen flex min-w-screen max-w-screen">
      <SideBar open={open} setOpen={setOpen} />
      <div className="grow  overflow-y-scroll relative ">
        <Nav open={open} setOpen={setOpen} />
        <div className=" min-h-full  bg-[#F8F9FD]">{children}</div>
      </div>
      {/* <div className="flex flex-row w-full h-full flex-1 relative">
        <div className="w-[20%] hidden lg:flex relative">
          <div className="w-[18%]  bg-lightBlue-100 overflow-y-auto sticky pt-20">
            <SideBar className="w-1/6 min-h-screen   hidden lg:flex flex-shrink-0   py-[2rem] px-8 border-r-[1px] border-r-[#C2C2C4]/[50%] fixed top-20 left-0" />
          </div>
        </div>
        <div className="w-full">
          <main className=" w-full lg:px-0 px-0  pt-20  h-full">
            {children}
          </main>
        </div>
      </div>  */}
    </div>
  );
}

{
  /* <div className="h-full min-h-screen max-h-screen flex min-w-screen max-w-screen">
<Sidebar  />
<div className="grow  overflow-y-scroll relative ">
  <Navbar  />
  <div className=" min-h-full p-[10px] lg:p-[30px] bg-[#F8F9FD]">
    <Outlet />
  </div>
</div>

</div> */
}
