import type { Metadata } from "next";
import Nav from "@/components/Layout/Nav";
import SideBar from "@/components/Layout/SideBar";

export const metadata: Metadata = {
  title: "Apodex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col h-full">
      <Nav />
      <div className="flex w-full h-full flex-1  py-2 px-6">
        <SideBar className="w-1/6 h-full flex flex-col justify-between p-[1rem]" />

        <main className="w-5/6 h-full">{children}</main>
      </div>
    </div>
  );
}
