import type { Metadata } from "next";
import Nav from "@/components/Layout/Nav";
import SideBar from "@/components/Layout/SideBar";

export const metadata: Metadata = {
  title: "Apodex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col h-full">
      <Nav />
      <div className="flex w-full h-full flex-1">
        <SideBar className="w-1/6 h-full  flex-col hidden lg:flex flex-shrink-0 justify-between py-[2rem] px-8 border-r-[1px] border-r-[#C2C2C4]/[50%] " />
        <main className="lg:w-5/6 w-full h-full">{children}</main>
      </div>
    </div>
  );
}